<?php
/**
 * Title: Digit Finance Homepage
 * Slug: digit-finance/homepage
 * Categories: featured
 * Block Types: core/post-content
 * Description: The editable Digit Finance homepage assembled from core blocks.
 *
 * @package DigitFinance
 */

$asset = static fn( string $file ): string => esc_url( get_theme_file_uri( 'assets/' . $file ) );
?>

<!-- wp:group {"tagName":"main","className":"df-home","layout":{"type":"default"}} -->
<main class="wp-block-group df-home">
<!-- wp:group {"tagName":"section","anchor":"top","className":"df-hero","layout":{"type":"constrained","wideSize":"1540px"}} -->
<section id="top" class="wp-block-group df-hero">
<!-- wp:group {"className":"df-hero-meta","layout":{"type":"flex","justifyContent":"space-between","flexWrap":"wrap"}} -->
<div class="wp-block-group df-hero-meta"><!-- wp:paragraph --><p>Financial advisory and fractional CFO support</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>AI-powered speed and board-level judgment for founders raising Seed to Series B.</p><!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:heading {"level":1,"className":"df-display df-hero-title"} --><h1 class="wp-block-heading df-display df-hero-title">Numbers that get you <em>funded</em></h1><!-- /wp:heading -->
<!-- wp:columns {"verticalAlignment":"stretch","className":"df-hero-stage"} --><div class="wp-block-columns are-vertically-aligned-stretch df-hero-stage">
<!-- wp:column {"verticalAlignment":"stretch","width":"54%","className":"df-hero-portrait"} --><div class="wp-block-column is-vertically-aligned-stretch df-hero-portrait"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="<?php echo $asset( 'sylvia-website.webp' ); ?>" alt="Sylvia Cebanu, founder of Digit Finance"/></figure><!-- /wp:image --></div><!-- /wp:column -->
<!-- wp:column {"verticalAlignment":"stretch","width":"46%","backgroundColor":"blue","textColor":"white","className":"df-hero-panel"} --><div class="wp-block-column is-vertically-aligned-stretch df-hero-panel has-white-color has-blue-background-color has-text-color has-background"><!-- wp:paragraph {"className":"df-kicker"} --><p class="df-kicker">01 / The Founder Problem</p><!-- /wp:paragraph -->
<!-- wp:quote {"className":"df-hero-quote"} --><blockquote class="wp-block-quote df-hero-quote"><p>Startup founders are brilliant at building their product, but when the numbers don't hold up—the cash flow, the model, the story investors need to hear—the best ideas in the world <strong>don't get funded.</strong></p></blockquote><!-- /wp:quote -->
<!-- wp:group {"className":"df-hero-panel-footer","layout":{"type":"flex","justifyContent":"space-between"}} --><div class="wp-block-group df-hero-panel-footer"><!-- wp:paragraph --><p>Fractional CFO</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>US · UK · EU</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
</div><!-- /wp:columns --></section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","anchor":"approach","backgroundColor":"navy","textColor":"white","className":"df-statement","layout":{"type":"constrained","wideSize":"1540px"}} --><section id="approach" class="wp-block-group df-statement has-white-color has-navy-background-color has-text-color has-background"><!-- wp:paragraph {"className":"df-section-label"} --><p class="df-section-label">The Partnership</p><!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"df-statement-copy"} --><p class="df-statement-copy">We pair AI-powered speed with board-level judgment to turn fast-moving startups into investor-ready businesses</p><!-- /wp:paragraph -->
<!-- wp:columns {"className":"df-metrics"} --><div class="wp-block-columns df-metrics"><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">€250M+</h3><!-- /wp:heading --><p>Capital raised by supported founders</p></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">100+</h3><!-- /wp:heading --><p>Startups supported from pre-seed to scale-up</p></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">14 yrs</h3><!-- /wp:heading --><p>Senior corporate finance experience</p></div><!-- /wp:column --></div><!-- /wp:columns --></section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","anchor":"services","className":"df-services","layout":{"type":"constrained","wideSize":"1540px"}} --><section id="services" class="wp-block-group df-services"><!-- wp:group {"className":"df-services-head","layout":{"type":"constrained","contentSize":"720px"}} --><div class="wp-block-group df-services-head"><!-- wp:heading {"className":"df-heading"} --><h2 class="wp-block-heading df-heading">How we work</h2><!-- /wp:heading --><p>From a critical one-off model to an ongoing seat at the table, the engagement adapts to the stage and decisions ahead.</p></div><!-- /wp:group -->
<!-- wp:group {"className":"df-service-list","layout":{"type":"default"}} --><div class="wp-block-group df-service-list">
<!-- wp:group {"className":"df-service-card","layout":{"type":"flex","flexWrap":"wrap","verticalAlignment":"center"}} --><div class="wp-block-group df-service-card"><!-- wp:paragraph {"className":"df-index"} --><p class="df-index">01.</p><!-- /wp:paragraph --><h3 class="wp-block-heading">Strategy hour</h3><p>Bring the messiest model, deck or board question and leave with a clear action plan.</p><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="/work-with-us/#strategy-hour">Explore ↗</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->
<!-- wp:group {"className":"df-service-card","layout":{"type":"flex","flexWrap":"wrap","verticalAlignment":"center"}} --><div class="wp-block-group df-service-card"><!-- wp:paragraph {"className":"df-index"} --><p class="df-index">02.</p><!-- /wp:paragraph --><h3 class="wp-block-heading">Financial model</h3><p>A bespoke bottom-up model built around your business, numbers and fundraising story. Delivered in 2 to 4 weeks.</p><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="/work-with-us/#financial-model">Explore ↗</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->
<!-- wp:group {"className":"df-service-card","layout":{"type":"flex","flexWrap":"wrap","verticalAlignment":"center"}} --><div class="wp-block-group df-service-card"><!-- wp:paragraph {"className":"df-index"} --><p class="df-index">03.</p><!-- /wp:paragraph --><h3 class="wp-block-heading">Fractional CFO</h3><p>Ongoing forecasting, cash flow, board reporting and senior financial leadership when it matters.</p><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="/work-with-us/#fractional-cfo">Explore ↗</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->
</div><!-- /wp:group --></section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","anchor":"process","className":"df-process","layout":{"type":"constrained","wideSize":"1540px"}} --><section id="process" class="wp-block-group df-process"><!-- wp:paragraph {"className":"df-section-label"} --><p class="df-section-label">How it works</p><!-- /wp:paragraph --><h2 class="wp-block-heading df-heading">What working together looks like</h2><!-- wp:columns {"className":"df-process-grid"} --><div class="wp-block-columns df-process-grid">
<!-- wp:column {"className":"df-process-step"} --><div class="wp-block-column df-process-step"><p class="df-index">01 / Start</p><h3 class="wp-block-heading">Discovery call</h3><p>A free call to understand the business, its stage and where the numbers need to go.</p></div><!-- /wp:column --><!-- wp:column {"className":"df-process-step"} --><div class="wp-block-column df-process-step"><p class="df-index">02 / Understand</p><h3 class="wp-block-heading">Deep dive</h3><p>A working session to map the model, drivers and assumptions so everything reflects reality.</p></div><!-- /wp:column --><!-- wp:column {"className":"df-process-step"} --><div class="wp-block-column df-process-step"><p class="df-index">03 / Build</p><h3 class="wp-block-heading">Build &amp; review</h3><p>Sylvia builds, then walks you through every number and the thinking behind it.</p></div><!-- /wp:column --><!-- wp:column {"className":"df-process-step"} --><div class="wp-block-column df-process-step"><p class="df-index">04 / Partner</p><h3 class="wp-block-heading">In your corner</h3><p>Ongoing support through board meetings, investor calls and the decisions between.</p></div><!-- /wp:column --></div><!-- /wp:columns --></section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","anchor":"about","className":"df-about","layout":{"type":"constrained","wideSize":"1540px"}} --><section id="about" class="wp-block-group df-about"><!-- wp:columns {"verticalAlignment":"center","className":"df-about-grid"} --><div class="wp-block-columns are-vertically-aligned-center df-about-grid"><!-- wp:column {"verticalAlignment":"center"} --><div class="wp-block-column is-vertically-aligned-center"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="<?php echo $asset( 'sylvia.webp' ); ?>" alt="Sylvia Cebanu"/></figure><!-- /wp:image --></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"center","className":"df-about-copy"} --><div class="wp-block-column is-vertically-aligned-center df-about-copy"><p class="df-section-label">About the founder</p><h2 class="wp-block-heading df-heading">Hi, I’m <em>Sylvia.</em></h2><p class="df-about-intro">The person founders call when the numbers stop matching the story.</p><p>Sylvia Cebanu is a fractional CFO and financial advisor to startups with 14 years of experience in corporate finance across the US, UK, and EU. Having built financial foundations for more than 100 startups from pre-seed to scale-up, Sylvia's work spans complex, fast-moving sectors where she builds the financial foundations founders need to make stronger decisions, raise capital and grow with confidence.</p><blockquote class="wp-block-quote df-about-pull"><p>You should feel proud of the business you're building, not just relieved it survived another quarter.</p></blockquote><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="/about/">Learn more about Sylvia ↗</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:column --></div><!-- /wp:columns --></section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"df-logos","layout":{"type":"constrained","wideSize":"1540px"}} --><section class="wp-block-group df-logos"><!-- wp:group {"className":"df-logos-inner","layout":{"type":"flex","flexWrap":"wrap","verticalAlignment":"center","justifyContent":"space-between"}} --><div class="wp-block-group df-logos-inner"><p>Trusted by ambitious founders across</p><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="<?php echo $asset( 'Logo-Fractional.png' ); ?>" alt="Fractional Group"/></figure><!-- /wp:image --><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="<?php echo $asset( 'upcelerator_logo.png' ); ?>" alt="Upcelerator"/></figure><!-- /wp:image --><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="<?php echo $asset( 'payall-logo.png' ); ?>" alt="Payall"/></figure><!-- /wp:image --></div><!-- /wp:group --></section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","anchor":"free","backgroundColor":"orange","textColor":"navy","className":"df-resource","layout":{"type":"constrained","wideSize":"1540px"}} --><section id="free" class="wp-block-group df-resource has-navy-color has-orange-background-color has-text-color has-background"><!-- wp:columns {"verticalAlignment":"center"} --><div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center"} --><div class="wp-block-column is-vertically-aligned-center"><p class="df-section-label">Free for early-stage founders</p><h2 class="wp-block-heading df-heading">Before the business, build the numbers.</h2><p>A plug-and-play Excel template for revenue, costs, cash flow and growth assumptions—plus a walkthrough of what investors actually look for.</p></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"center"} --><div class="wp-block-column is-vertically-aligned-center"><!-- wp:buttons {"layout":{"type":"flex","justifyContent":"right"}} --><div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"navy","textColor":"white","className":"df-resource-cta"} --><div class="wp-block-button df-resource-cta"><a class="wp-block-button__link has-white-color has-navy-background-color has-text-color has-background wp-element-button" href="/free-template/">Download the free template ↗</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:column --></div><!-- /wp:columns --></section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"df-testimonials","layout":{"type":"constrained","wideSize":"1540px"}} --><section class="wp-block-group df-testimonials"><p class="df-section-label">Founder perspective</p><h2 class="wp-block-heading df-heading">What founders say</h2><!-- wp:group {"className":"df-quote-list","layout":{"type":"default"}} --><div class="wp-block-group df-quote-list"><!-- wp:quote {"className":"df-quote-row"} --><blockquote class="wp-block-quote df-quote-row"><p>“Sylvia rebuilt our model from scratch and we walked into our Series A able to defend every number.”</p><cite><strong>Founder name</strong><br/>CEO, Company</cite></blockquote><!-- /wp:quote --><!-- wp:quote {"className":"df-quote-row"} --><blockquote class="wp-block-quote df-quote-row"><p>“The clarity she gave us cut weeks off our raise and changed how our board saw the business.”</p><cite><strong>Founder name</strong><br/>Founder, Company</cite></blockquote><!-- /wp:quote --><!-- wp:quote {"className":"df-quote-row"} --><blockquote class="wp-block-quote df-quote-row"><p>“Having Sylvia in the room for investor calls was the difference between hoping and knowing.”</p><cite><strong>Founder name</strong><br/>Co-founder, Company</cite></blockquote><!-- /wp:quote --></div><!-- /wp:group --></section><!-- /wp:group -->

<!-- wp:group {"tagName":"section","backgroundColor":"navy","textColor":"white","className":"df-closing","layout":{"type":"constrained","wideSize":"1540px"}} --><section class="wp-block-group df-closing has-white-color has-navy-background-color has-text-color has-background"><h2 class="wp-block-heading df-heading">Ready to make the numbers <em>work?</em></h2><!-- wp:columns {"verticalAlignment":"center","className":"df-closing-row"} --><div class="wp-block-columns are-vertically-aligned-center df-closing-row"><!-- wp:column {"verticalAlignment":"center"} --><div class="wp-block-column is-vertically-aligned-center"><p>Tell us where the business is going and what is getting in the way. We will make the next financial decision clearer.</p></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"center"} --><div class="wp-block-column is-vertically-aligned-center"><!-- wp:buttons {"layout":{"type":"flex","justifyContent":"right"}} --><div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"white","textColor":"navy"} --><div class="wp-block-button"><a class="wp-block-button__link has-navy-color has-white-background-color has-text-color has-background wp-element-button" href="mailto:hello@digitfinance.com">Book a call ↗</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:column --></div><!-- /wp:columns --></section><!-- /wp:group -->
</main>
<!-- /wp:group -->
