<?php
/**
 * Title: Digit Finance — Hero and Partnership
 * Slug: digit-finance/homepage-hero-partnership
 * Categories: featured
 * Block Types: core/post-content
 * Description: The editable first two sections of the Digit Finance homepage.
 *
 * @package DigitFinance
 */
?>
<!-- wp:group {"tagName":"section","anchor":"top","className":"df-hero","layout":{"type":"constrained","wideSize":"1540px"}} --><section id="top" class="wp-block-group df-hero"><!-- wp:group {"className":"df-hero-meta","layout":{"type":"flex","justifyContent":"space-between","flexWrap":"wrap"}} --><div class="wp-block-group df-hero-meta"><!-- wp:paragraph --><p>Financial advisory and fractional CFO support</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>AI-powered speed and board-level judgment for founders raising Seed to Series B.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:heading {"level":1,"className":"df-display df-hero-title"} --><h1 class="wp-block-heading df-display df-hero-title">Numbers that get you <em>funded</em></h1><!-- /wp:heading --><!-- wp:columns {"verticalAlignment":"stretch","className":"df-hero-stage"} --><div class="wp-block-columns are-vertically-aligned-stretch df-hero-stage"><!-- wp:column {"verticalAlignment":"stretch","width":"54%","className":"df-hero-portrait"} --><div class="wp-block-column is-vertically-aligned-stretch df-hero-portrait"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/sylvia-website.webp' ) ); ?>" alt="Sylvia Cebanu, founder of Digit Finance"/></figure><!-- /wp:image --></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"stretch","width":"46%","backgroundColor":"blue","textColor":"white","className":"df-hero-panel"} --><div class="wp-block-column is-vertically-aligned-stretch df-hero-panel has-white-color has-blue-background-color has-text-color has-background"><!-- wp:paragraph {"className":"df-kicker"} --><p class="df-kicker">01 / The Founder Problem</p><!-- /wp:paragraph --><!-- wp:quote {"className":"df-hero-quote"} --><blockquote class="wp-block-quote df-hero-quote"><p>Startup founders are brilliant at building their product, but when the numbers don't hold up—the cash flow, the model, the story investors need to hear—the best ideas in the world <strong>don't get funded.</strong></p></blockquote><!-- /wp:quote --><!-- wp:group {"className":"df-hero-panel-footer","layout":{"type":"flex","justifyContent":"space-between"}} --><div class="wp-block-group df-hero-panel-footer"><!-- wp:paragraph --><p>Fractional CFO</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>US · UK · EU</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --></section><!-- /wp:group -->
<!-- wp:group {"tagName":"section","anchor":"approach","backgroundColor":"navy","textColor":"white","className":"df-statement","layout":{"type":"constrained","wideSize":"1540px"}} --><section id="approach" class="wp-block-group df-statement has-white-color has-navy-background-color has-text-color has-background"><!-- wp:paragraph {"className":"df-section-label"} --><p class="df-section-label">The Partnership</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"df-statement-copy"} --><p class="df-statement-copy">We pair AI-powered speed with board-level judgment to turn fast-moving startups into investor-ready businesses</p><!-- /wp:paragraph --><!-- wp:columns {"className":"df-metrics"} --><div class="wp-block-columns df-metrics"><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">€250M+</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Capital raised by supported founders</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">100+</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Startups supported from pre-seed to scale-up</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">14 yrs</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Senior corporate finance experience</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></section><!-- /wp:group -->
